org: estuardoo
# ====== TablaTransaccion ======
TablaTransaccion:
Type: AWS::DynamoDB::Table
Properties:
TableName: TablaTransaccion
BillingMode: PAY_PER_REQUEST
AttributeDefinitions:
- AttributeName: TransaccionID
AttributeType: S
- AttributeName: ComercioID
AttributeType: N
- AttributeName: FechaHoraISO
AttributeType: S
- AttributeName: FraudeFecha
AttributeType: S
- AttributeName: IdTransaccionOrigen
AttributeType: S
- AttributeName: ClienteID
AttributeType: N
KeySchema:
- AttributeName: TransaccionID
KeyType: HASH
GlobalSecondaryIndexes:
- IndexName: GSI_Comercio_Fecha
KeySchema:
- AttributeName: ComercioID
KeyType: HASH
- AttributeName: FechaHoraISO
KeyType: RANGE
Projection:
ProjectionType: ALL
- IndexName: GSI_Comercio_Fraude
KeySchema:
- AttributeName: ComercioID
KeyType: HASH
- AttributeName: FraudeFecha
KeyType: RANGE
Projection:
ProjectionType: ALL
- IndexName: GSI_IdTransOrigen
KeySchema:
- AttributeName: IdTransaccionOrigen
KeyType: HASH
Projection:
ProjectionType: ALL
- IndexName: GSI_Cliente_Fecha
KeySchema:
- AttributeName: ClienteID
KeyType: HASH
- AttributeName: FechaHoraISO
KeyType: RANGE
Projection:
ProjectionType: ALL